default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000
  min_messages: warning

development:
  <<: *default
  database: infoeducatie_development
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("DB_USER", ENV.fetch("USER", "postgres")) %>
  password: <%= ENV["DB_PASSWORD"] %>

test:
  <<: *default
  database: infoeducatie_test
  host: <%= ENV.fetch("DB_HOST", "localhost") %>
  username: <%= ENV.fetch("DB_USER", ENV.fetch("USER", "postgres")) %>
  password: <%= ENV["DB_PASSWORD"] %>

staging:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
