require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ContestantsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Contestant. As you add validations to Contestant, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ContestantsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all contestants as @contestants" do
      contestant = Contestant.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:contestants)).to eq([contestant])
    end
  end

  describe "GET #show" do
    it "assigns the requested contestant as @contestant" do
      contestant = Contestant.create! valid_attributes
      get :show, {:id => contestant.to_param}, valid_session
      expect(assigns(:contestant)).to eq(contestant)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Contestant" do
        expect {
          post :create, {:contestant => valid_attributes}, valid_session
        }.to change(Contestant, :count).by(1)
      end

      it "assigns a newly created contestant as @contestant" do
        post :create, {:contestant => valid_attributes}, valid_session
        expect(assigns(:contestant)).to be_a(Contestant)
        expect(assigns(:contestant)).to be_persisted
      end

      it "redirects to the created contestant" do
        post :create, {:contestant => valid_attributes}, valid_session
        expect(response).to redirect_to(Contestant.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved contestant as @contestant" do
        post :create, {:contestant => invalid_attributes}, valid_session
        expect(assigns(:contestant)).to be_a_new(Contestant)
      end

      it "re-renders the 'new' template" do
        post :create, {:contestant => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested contestant" do
        contestant = Contestant.create! valid_attributes
        put :update, {:id => contestant.to_param, :contestant => new_attributes}, valid_session
        contestant.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested contestant as @contestant" do
        contestant = Contestant.create! valid_attributes
        put :update, {:id => contestant.to_param, :contestant => valid_attributes}, valid_session
        expect(assigns(:contestant)).to eq(contestant)
      end

      it "redirects to the contestant" do
        contestant = Contestant.create! valid_attributes
        put :update, {:id => contestant.to_param, :contestant => valid_attributes}, valid_session
        expect(response).to redirect_to(contestant)
      end
    end

    context "with invalid params" do
      it "assigns the contestant as @contestant" do
        contestant = Contestant.create! valid_attributes
        put :update, {:id => contestant.to_param, :contestant => invalid_attributes}, valid_session
        expect(assigns(:contestant)).to eq(contestant)
      end

      it "re-renders the 'edit' template" do
        contestant = Contestant.create! valid_attributes
        put :update, {:id => contestant.to_param, :contestant => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end
end
